HelpChat/ChatChat

api/build.gradle.kts
api/src/main/java/at/helpch/chatchat/api/User.java
build-logic/src/main/kotlin/chatchat.base-conventions.gradle.kts
gradle.properties
gradle/libs.versions.toml
plugin/build.gradle.kts
plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
plugin/src/main/java/at/helpch/chatchat/command/MainCommand.java
plugin/src/main/java/at/helpch/chatchat/command/ReloadCommand.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigFactory.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
plugin/src/main/java/at/helpch/chatchat/config/FormatsHolder.java
plugin/src/main/java/at/helpch/chatchat/format/ChatFormat.java
plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
plugin/src/main/java/at/helpch/chatchat/user/ChatUser.java
plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java

plugin actually builds now. 
formats are here, with some commands
all has been tested :)

formats!!!

---

plugin/src/main/java/at/helpch/chatchat/command/ChatChatCommand.java
plugin/src/main/java/at/helpch/chatchat/command/MainCommand.java
plugin/src/main/java/at/helpch/chatchat/command/ReloadCommand.java
plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java

In the future this will be even better, as you will be able to declare global things for a specific command and apply to all subcommands even being in a different class, that's why we should use inheritance for it.
This also reduces the boilerplate as you won't be needing to declare, command, alias, description, etc on every single class.

Small reduction of boiler plate for commands

---

api/src/main/java/at/helpch/chatchat/api/User.java
plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/command/ReloadCommand.java
plugin/src/main/java/at/helpch/chatchat/command/ReplyCommand.java
plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
plugin/src/main/java/at/helpch/chatchat/user/ChatUser.java

Added reply command
- Reload command now requires a permission
- made sure that players can't message themselves in the message command
- added tab completion for all online players when using the message command

Added reply command

---

plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java

For some reason I made it so if someone is listening to the ChatChatEvent and replacing the format, the user's format would be completely changed. I fixed this with this pr.

Fixed user's format being changed whenever they talk

---

plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
plugin/src/main/java/at/helpch/chatchat/config/ChannelsHolder.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigFactory.java
plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
plugin/src/main/java/at/helpch/chatchat/config/FormatsHolder.java
plugin/src/main/java/at/helpch/chatchat/config/SettingsHolder.java
plugin/src/main/java/at/helpch/chatchat/format/DefaultFormatFactory.java
plugin/src/main/java/at/helpch/chatchat/format/PMFormat.java
plugin/src/main/resources/channels.yml
plugin/src/main/resources/formats.yml
plugin/src/main/resources/settings.yml

makes them a little nicer :)
added a little header to each file for the wiki page (whenever thatll be ready)
added comments to the resource files.
configurate doesn't yet support comments in yaml (except the header), so this will have to do for now

updated the default config formats

---

build-logic/src/main/kotlin/chatchat.base-conventions.gradle.kts
build-logic/src/main/kotlin/chatchat.parent-conventions.gradle.kts
plugin/build.gradle.kts

removed the need for mavenLocal
added the paper repo to the base conventions

fixed issue that required spigot api to be in mavenLocal

---

api/src/main/java/at/helpch/chatchat/api/Channel.java
api/src/main/java/at/helpch/chatchat/api/User.java
api/src/main/java/at/helpch/chatchat/api/event/ChatChatEvent.java
plugin/build.gradle.kts
plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
plugin/src/main/java/at/helpch/chatchat/command/SwitchChannelCommand.java
plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
plugin/src/main/java/at/helpch/chatchat/config/mapper/ChannelMapper.java
plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java
plugin/src/main/java/at/helpch/chatchat/user/ConsoleUser.java
plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java

- Made `Channel` implement `Audience` instead of `ForwardingAudience`
- Remove `ChatChatEvent#recipients`
- Moved `User#canSee` to `Channel#isUseableBy`
- Remove `User#canUse`
- Use `Audience#sendMessage(Identity, Component)` to send chat messages
- Add default permissions in `bukkit.yml`

Implement Audience further

---

gradle/libs.versions.toml
plugin/build.gradle.kts
plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/channel/AbstractChannel.java
plugin/src/main/java/at/helpch/chatchat/channel/ChannelTypeRegistry.java
plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigFactory.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
plugin/src/main/java/at/helpch/chatchat/config/holders/ChannelsHolder.java
plugin/src/main/java/at/helpch/chatchat/config/holders/FormatsHolder.java
plugin/src/main/java/at/helpch/chatchat/config/holders/SettingsHolder.java
plugin/src/main/java/at/helpch/chatchat/config/mapper/ChannelMapMapper.java
plugin/src/main/java/at/helpch/chatchat/config/mapper/ChannelMapper.java
plugin/src/main/java/at/helpch/chatchat/towny/AbstractTownyChannel.java
plugin/src/main/java/at/helpch/chatchat/towny/TownyNationChannel.java
plugin/src/main/java/at/helpch/chatchat/towny/TownyTownChannel.java
plugin/src/main/java/at/helpch/chatchat/util/ChannelUtils.java
plugin/src/main/resources/channels.yml

- Changes to support alternative channel implementations
- Initial towny support as an example

Support alternative channel implementations

---

plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
plugin/src/main/java/at/helpch/chatchat/command/MainCommand.java
plugin/src/main/java/at/helpch/chatchat/command/ReloadCommand.java
plugin/src/main/java/at/helpch/chatchat/command/ReplyCommand.java
plugin/src/main/java/at/helpch/chatchat/command/SocialSpyCommand.java
plugin/src/main/java/at/helpch/chatchat/command/SwitchChannelCommand.java
plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigFactory.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java
plugin/src/main/java/at/helpch/chatchat/config/mapper/MiniMessageComponentMapper.java
plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
plugin/src/main/java/at/helpch/chatchat/util/MessageUtils.java
plugin/src/main/resources/messages.yml

Added a messages.yml file for all message settings
These settings are automatically mapped to Components via the MiniMessageComponentMapper class to serialize/deserialize
Made some minor changes to the main and reload command too

Added configurable messages

---

api/src/main/java/at/helpch/chatchat/api/Channel.java
plugin/build.gradle.kts
plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
plugin/src/main/java/at/helpch/chatchat/config/holders/SettingsHolder.java
plugin/src/main/java/at/helpch/chatchat/towny/AbstractTownyChannel.java
plugin/src/main/java/at/helpch/chatchat/util/MentionUtils.java
plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
plugin/src/main/resources/settings.yml

Includes mentioning (per-user or here/everyone/channel).

Per-player messages + mentioning

---

api/src/main/java/at/helpch/chatchat/api/Hook.java
gradle/libs.versions.toml
plugin/build.gradle.kts
plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/hooks/HookManager.java
plugin/src/main/java/at/helpch/chatchat/hooks/dsrv/ChatChatDsrvHook.java
plugin/src/main/java/at/helpch/chatchat/hooks/towny/AbstractTownyChannel.java
plugin/src/main/java/at/helpch/chatchat/hooks/towny/ChatChatTownyHook.java
plugin/src/main/java/at/helpch/chatchat/hooks/towny/TownyNationChannel.java
plugin/src/main/java/at/helpch/chatchat/hooks/towny/TownyTownChannel.java
plugin/src/main/resources/channels.yml

Also added DiscordSRV support as a guinea pig

Hooks, a proper way to interact with other plugins

---

gradle/libs.versions.toml
plugin/src/main/java/at/helpch/chatchat/hooks/HookManager.java
plugin/src/main/java/at/helpch/chatchat/hooks/dsrv/ChatChatDsrvHook.java
plugin/src/main/java/at/helpch/chatchat/hooks/dsrv/DsrvListener.java

i can only assume this works as there are no errors on startup now

fixed error if dsrv wasnt installed

---

gradle/libs.versions.toml
plugin/src/main/resources/channels.yml
plugin/src/main/resources/formats.yml
plugin/src/main/resources/settings.yml

- Updated the `format` setting to `parts` 
- changed the `%message%` placeholder to `<message>` 
Added a little more comments for extra documentation too

updated resource files

---

plugin/build.gradle.kts
plugin/src/main/java/at/helpch/chatchat/util/ChannelUtils.java
plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
plugin/src/main/java/at/helpch/chatchat/util/ItemUtils.java
plugin/src/main/java/at/helpch/chatchat/util/MentionUtils.java
plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
plugin/src/main/java/at/helpch/chatchat/util/MessageUtils.java
plugin/src/main/java/at/helpch/chatchat/util/StringUtils.java

- Reworked the default permissions listed in plugin.yml
- Made all util classes final and also made a private constructor for each that throws.
- Switched message from hardcoded to configurable.

Some small changes and improvements

---

api/src/main/java/at/helpch/chatchat/api/Channel.java
plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/channel/AbstractChannel.java
plugin/src/main/java/at/helpch/chatchat/channel/ChannelTypeRegistry.java
plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
plugin/src/main/java/at/helpch/chatchat/command/SwitchChannelCommand.java
plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
plugin/src/main/java/at/helpch/chatchat/config/mapper/ChannelMapper.java
plugin/src/main/java/at/helpch/chatchat/hooks/towny/AbstractTownyChannel.java
plugin/src/main/java/at/helpch/chatchat/hooks/towny/TownyNationChannel.java
plugin/src/main/java/at/helpch/chatchat/hooks/towny/TownyTownChannel.java
plugin/src/main/resources/channels.yml

Resolves #62 
Essentially just changed all the Channel toggle commands from a `String` to a `List<String>`

Allow multiple Channel toggle commands

---

plugin/src/main/java/at/helpch/chatchat/config/mapper/ChannelMapper.java

Fixed optional values not actually being optional.

---

plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/command/WhisperToggleCommand.java

- fix typo in command name togglepm
- fix an issue where if only 1 channel command name, it would throw an error

fix command issues

---

plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java

This was done to match DeluxeChat functionality. Fixes #67

Added relational placeholders support in normal chat messages

---

plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java

Cancel the AsyncPlayerChatEvent if the ChatChatEvent fired with it is canceled.  

---

gradle/wrapper/gradle-wrapper.properties
plugin/build.gradle.kts

stop shading essentials

---

gradle/libs.versions.toml

Fixes #101 
Tested on 1.19.1, appears to fix the hover issue:

Bumped adventure-platform version to 4.1.2 (Fixes #101)

---

.editorconfig

Everyone should make sure they have the Editorconfig plugin enabled

add more IJ specific settings to .editorconfig

---

api/src/main/java/at/helpch/chatchat/api/ChatUser.java
plugin/build.gradle.kts
plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/command/MentionToggleCommand.java
plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java
plugin/src/main/java/at/helpch/chatchat/data/impl/gson/ChatUserAdapter.java
plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java
plugin/src/main/java/at/helpch/chatchat/util/MentionUtils.java

Adds a `/togglemention` command with a `/toggleping` alias.
Marked as a draft for now, because this should wait to be merged until the storage system is implemented.
Resolves #108

Add a Toggle Ping/Mention command

---

plugin/src/main/java/at/helpch/chatchat/hooks/HookManager.java

Fixed hooks only registering sometimes. Ooops

---

plugin/build.gradle.kts
plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/command/FormatTestCommand.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java

Added a format test command

---

plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java

Fixed order of privat messages and spy messages being random

---

plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java

Fixed messages being unnecesarely registered on every plugin reload

---

plugin/src/main/java/at/helpch/chatchat/util/ItemUtils.java

We are going to only support 1.16.5+ from now on so there's no need for that anymore.
Closes #76

Reverted the 1.13.3 support commit

---

plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/cache/ExpiringCache.java
plugin/src/main/java/at/helpch/chatchat/config/holders/SettingsHolder.java
plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java
plugin/src/main/resources/settings.yml

Can be set to a negative number to disable
Closes #129

Made the last user expiring time customizable

---

plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java

Resolves #132 
@BlitzOffline double check the logic in `WhisperCommand.java` and make sure that's how you want it

Ignored Players respect PMs

---

plugin/src/main/java/at/helpch/chatchat/util/ItemUtils.java

Fixed hex colors not working in the <item> tag

---

plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java

Fixed tags not caring about permissions in user messages

---

plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/command/DumpCommand.java
plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java
plugin/src/main/java/at/helpch/chatchat/util/DumpUtils.java
plugin/src/main/resources/messages.yml

Closes #128 
The command takes in an optional parameter that is basically the file that you want to dump.
1 extra check we might want to add to the parameter is if the file is directly in the ChatChat/ directory and not in a subdirectory since right now in theory any file in any subdirectory of the ChatChat directory can be accessed by it as long as it has permissions and the file exists. We might also want to keep this for maybe user dumps?

Added a dump command

---

plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java

Fixed wrong message being sent when messaging offline player

---

plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java

Fixed PMSendEvent always being called as msg instead of reply

---

plugin/src/main/java/at/helpch/chatchat/data/impl/gson/ChatUserAdapter.java
plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java

Switch the user to the correct channel if they no longer have permission for the current one.
(Requires proper testing)

ChatListener change

---

plugin/src/main/java/at/helpch/chatchat/config/ConfigFactory.java
plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
plugin/src/main/java/at/helpch/chatchat/config/holder/GlobalFormatsHolderImpl.java
plugin/src/main/java/at/helpch/chatchat/config/holder/MentionSettingsHolder.java
plugin/src/main/java/at/helpch/chatchat/config/holder/PMSettingsHolder.java

fix format serialization
this PR is the same as #169, just a nicer way

fix format serialization

---

gradle/libs.versions.toml

Upgraded the spigot and adventure platform versions with which the plugin is compiled to fix some issues on 1.19.3

Upgrade platform version

---

plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java

Somehow I managed to commit without registering the command. I have no idea how tho.
Closes #177

Registered the unignore command

---

plugin/build.gradle.kts
plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/command/IgnoreListCommand.java
plugin/src/main/java/at/helpch/chatchat/config/holder/MessagesHolder.java

Added `/ignorelist` command

---

plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java

Before this change, if a user had access to social spy and had it enabled, they would receive the spy message even when they were the sender or the recipient of that message. This ended up with basically duplicated chat messages for those users.
Closes #184

Fix spy messages being sent to the message recipient and senders

---

plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
plugin/src/main/java/at/helpch/chatchat/hooks/towny/AbstractTownyChannel.java

Pull Request inspired by https://github.com/Akiranya/ChatChat

Fixed a few issues with towny.

---

api/src/main/java/at/helpch/chatchat/api/placeholder/MiniPlaceholderManager.java
plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
plugin/src/main/java/at/helpch/chatchat/placeholder/MiniPlaceholderManagerImpl.java

Clear old MiniPlaceholders on config reload

---

plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java

Update selected channels on config reload

---

plugin/src/main/java/at/helpch/chatchat/config/mapper/AddonsMapper.java

Simple fix, someone may have just forgotten to update when copying and pasting :3

Fixed grief prevention in the exstentions config
