HelpChat/ChatChat

- api/src/main/java/at/helpch/chatchat/api/Format.java
- plugin/src/main/java/at/helpch/chatchat/command/ReloadCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/config/ConfigFactory.java
- plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
- plugin/src/main/java/at/helpch/chatchat/config/FormatsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/SettingsHolder.java
- plugin/src/main/java/at/helpch/chatchat/format/ChatFormat.java
- plugin/src/main/java/at/helpch/chatchat/format/DefaultFormatFactory.java
- plugin/src/main/java/at/helpch/chatchat/format/PMFormat.java
- plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
Reworked the config factory so that it will now create a default config object if there is something wrong with the config file, this means that when calling any of the getters in the ConfigManager class, the returned type will be NotNull.
As for the changes to the Format classes:
- I've removed the get/set method prefixes here, as they are redundant tbh.
- The format classes are pretty much now immutable, as calling priority(int)/parts(List) will return a newly-created Format object with the changes. the only thing thats not fully mutable is the Configurate part of class... oh well.
- Instead of creating a new default format each time its needed, ive cached them so they can be retrieved easily.
- The default format creator methods have been moved to their own class to remove some clutter …
> Reworked the config manager/factory + lots of changes to the Format classes

- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
- Added a new parseFormat method that takes in a sender and a recipient
- Removed the recipient parsing of placeholders from the method that doesn't take in a recipient
- Fixed private messages parsing the placeholders just for the sender or receiver depending on the format.
Edit: One "small" problem this has is that it replaces all instances of %recipient_ to % even tho there might be nothing after it. We would need an entire parser for this to be fixed, similar to what PAPI has I guess.
> Fixed the recipient placeholders in private messaging

- gradle/libs.versions.toml
- plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
- plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
- plugin/src/main/java/at/helpch/chatchat/command/ChatChatCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/MainCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/ReloadCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/config/SettingsHolder.java
- plugin/src/main/java/at/helpch/chatchat/format/DefaultFormatFactory.java
- plugin/src/main/java/at/helpch/chatchat/format/PMFormat.java
- plugin/src/main/java/at/helpch/chatchat/listener/PlayerListener.java
- plugin/src/main/java/at/helpch/chatchat/placeholder/ChatPlaceholders.java
- plugin/src/main/java/at/helpch/chatchat/util/ChannelUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
- plugin/src/main/resources/formats.yml
- Added a plugin enable and plugin disable message to the console
- Fixed whisper message being limited to 1 word (in this case a word means any chat until a space)
- Removed a bunch of unused imports
- Removed unused variable
- Renamed "receiver" to recipient everywhere to make it more consistent
- Added the %message% placeholder in the default format. This is mostly to help while we still work on the plugin because I Do know all default formats will be reworked before release
- Started work on an internal PlaceholderAPI expansion. Currently only has 2 placeholder.
- Bumped PlaceholderAPI dependency version to latest PAPI release.
That's about it. I tried to keep the commit naming very useful as well so you can tell what commit does what.
> Small changes and improvements + start of PAPI Expansion.

- plugin/src/main/java/at/helpch/chatchat/command/ReplyCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
As the title mentions, we used to parse the message sent by an user just like it was part of the format so minimessage tags would be parsed. This would allow everyone to use tags like <rainbow> in their messages.
> Fixed MiniMessage tags being parsed in messages sent by users (both private and public messages)

- api/src/main/java/at/helpch/chatchat/api/Channel.java
- api/src/main/java/at/helpch/chatchat/api/Format.java
- plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
- plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/config/ConfigFactory.java
- plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
- plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
- plugin/src/main/java/at/helpch/chatchat/config/holders/ChannelsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/holders/FormatsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/holders/SettingsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/mapper/ChannelMapper.java
- plugin/src/main/java/at/helpch/chatchat/config/mapper/ChatFormatMapper.java
- plugin/src/main/java/at/helpch/chatchat/config/mapper/PMFormatMapper.java
- plugin/src/main/java/at/helpch/chatchat/format/ChatFormat.java
- plugin/src/main/java/at/helpch/chatchat/format/DefaultFormatFactory.java
- plugin/src/main/java/at/helpch/chatchat/format/PMFormat.java
- plugin/src/main/java/at/helpch/chatchat/placeholder/ChatPlaceholders.java
- plugin/src/main/java/at/helpch/chatchat/user/ChatUser.java
- plugin/src/main/java/at/helpch/chatchat/util/ChannelUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
The config objects now have custom serializers. This means that we no longer require a 0-args constructor and allows for the objects to be fully immutable. Not only this, but their config key is now stored inside of Format#name() or Channel#name() for easy access.
The default channel/format is now set inside of a static variable and is updated on reload. These no longer require a permission too.
> some changes to the config / format+channels

- api/src/main/java/at/helpch/chatchat/api/event/ChatChatEvent.java
- api/src/main/java/at/helpch/chatchat/api/event/PMSendEvent.java
- plugin/src/main/java/at/helpch/chatchat/command/ReplyCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
- Added a PMSendEvent, fired when a private message is sent. (there is a way to tell if it was a reply or just a normal PM as well)
- Made it so the message in ChatChatEvent is Component. This way we can promote usage of Components over Strings to other developers as well.
- Added some missing @NotNull annotations and some final keywords.
- Added getter for channel in ChatChatEvent
- Added relational PAPI placeholder support. Currently it only works in PMs.
> Added a PMSendEvent and some more.

- api/src/main/java/at/helpch/chatchat/api/event/PMSendEvent.java
- plugin/src/main/java/at/helpch/chatchat/command/ReplyCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/SwitchChannelCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
- plugin/src/main/java/at/helpch/chatchat/placeholder/ChatPlaceholders.java
- plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java
- plugin/src/main/java/at/helpch/chatchat/util/ChannelUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
- plugin/src/main/java/at/helpch/chatchat/util/StringUtils.java
- Users now require the chatchat.utf permission to send messages that contain "illegal chars". It does exactly what DeluxeChat used to, which is to allow chars 0-128 + 167(ascii)
- Added ability to use the `/channel-name` command to send a message: /<channel-name> [message]. This does not switch the channel. Only sends the message. We might need an extra perm for this? Its basically an alternative to the quick prefix.
- Temporarily switch user's channel when they send a message. This is to fix issues when player send message using quick prefix or the /<channel-name> [message] command. This does fix #27 
- Removed unused imports :)
> Added permission to use UTF chars in messages and some more.

- api/src/main/java/at/helpch/chatchat/api/event/ChatChatEvent.java
- plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
- plugin/src/main/java/at/helpch/chatchat/config/holders/SettingsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/mapper/ChannelMapMapper.java
- plugin/src/main/java/at/helpch/chatchat/config/mapper/ChannelMapper.java
- plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
- plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/ItemUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
- plugin/src/main/java/at/helpch/chatchat/util/MessageUtils.java
- plugin/src/main/resources/settings.yml
- Fixed the channel quick prefix being removed even if an user had no permission to talk in that specific channel.
- Added support for minimessage tags inside messages. They're all permission based. (chatchat.tag.<option>)
- Moved the URL replacer (the thing that makes url clickable) in the message processor. Seemed to make a bit more sense.
- Added a custom <item> tag that will display the item hold in hand. Its customizable from the settings.
A few notes:
With the addition of the item tag, the plugin will only work 1.13+ since it uses Player#getInventory#getItemInMainHand and this happens every time a message is processed. Since we discussed that's going to be our targeted version anyways, I don't really see why we'd have a fallback. At most tho, we might want to use PAPI's version …
> Fixes and improvements.

- plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
- plugin/src/main/java/at/helpch/chatchat/util/StringUtils.java
- Added permissions to block mentions coming to user (global or personal)
- Added permission to override that block
- Fixed personal mentions only showing to the receiver and not the sender as well
There's still a couple problems with the mention system however:
- When an item is named <mention-prefix><online-player-name/everyone> and the player uses the item tag inside their message, it will act like a mention.
- When the chat message has gradients or rainbows the mentions won't be picked up. I believe this is the same problem we used to have for the %message% tag (might need to confirm with the kyori team again if its a bug or not. I Don't remember what the outcome of the discussion last time was.) EDIT: After some tests turns out the problem is that the Component#replaceText method …
> Reworked the mention system

- api/src/main/java/at/helpch/chatchat/api/ChatUser.java
- plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperToggleCommand.java
- plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java
- plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
- plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
- plugin/src/main/resources/messages.yml
- The chat listener is at the highest priority now. (The chat formatting plugin should be the last to handle the messages imo)
- Added better formats (appending the parts before deserialization)
- Added a way to toggle personal DMs. (unfortunately it resets when the player reconnects. same as channels since we're not storing anything user related yet)
- Cleanse messages before processing them. This is possibly a temporary solution until a better one is found. This just removes legacy color codes from the actual message.
> Better Formats, DM Toggling

- api/src/main/java/at/helpch/chatchat/api/Format.java
- gradle/libs.versions.toml
- plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
- plugin/src/main/java/at/helpch/chatchat/config/mapper/ChatFormatMapper.java
- plugin/src/main/java/at/helpch/chatchat/config/mapper/PMFormatMapper.java
- plugin/src/main/java/at/helpch/chatchat/format/ChatFormat.java
- plugin/src/main/java/at/helpch/chatchat/format/DefaultFormatFactory.java
- plugin/src/main/java/at/helpch/chatchat/format/PMFormat.java
- plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
- plugin/src/main/java/at/helpch/chatchat/placeholder/ChatPlaceholders.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
- plugin/src/main/resources/formats.yml
- plugin/src/main/resources/settings.yml
- Upgraded adventure platform to 4.1.0 from 4.0.1
- Fixed default internal format using %message% instead of <message> (Closes #59 )
- Default formats are now LinkedHashMap
- Improved default files
- Switched from a shitty %recipient_PAPI-PLACEHOLDER% parser to a nice <recipient:PAPI-PLACEHOLDER> minimessage tag
- Added more internal placeholders: `%chatchat_channel_message_prefix%`, `%chatchat_social_spy_enabled%`, `%chatchat_private_messages_enabled%` and `%chatchat_private_messages_recipient%`. This means full parity with DeluxeTag's placeholders.
- Allowed some placeholders to work for a null target as well. They'll just be parsed for the ConsoleUser.
Note: \<recipient\> is also a placeholder and will return the player's name.
> Made the format parts a Map<String, List<String>>

- api/src/main/java/at/helpch/chatchat/api/exception/ChatChatException.java
- api/src/main/java/at/helpch/chatchat/api/hook/Hook.java
- gradle/libs.versions.toml
- plugin/build.gradle.kts
- plugin/src/main/java/at/helpch/chatchat/hooks/HookManager.java
- plugin/src/main/java/at/helpch/chatchat/hooks/dsrv/ChatChatDsrvHook.java
- plugin/src/main/java/at/helpch/chatchat/hooks/towny/ChatChatTownyHook.java
- plugin/src/main/java/at/helpch/chatchat/hooks/vanish/EssentialsVanishHook.java
- plugin/src/main/java/at/helpch/chatchat/hooks/vanish/SuperVanishHook.java
- plugin/src/main/java/at/helpch/chatchat/hooks/vanish/VanillaVanishHook.java
- plugin/src/main/java/at/helpch/chatchat/listener/EssentialsVanishListener.java
- plugin/src/main/java/at/helpch/chatchat/util/ItemUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/VersionHelper.java
ChatChat was using some methods and events that were not available on all 1.13+ versions and was just throwing errors. This PR should fix most if not all of those.
- Fixed usage of PlayerHideEvent on versions older than 1.19
- Fixed usage of Material#isAir on versions older than 1.14
- Added a direct EssentialsX vanish hook
> Fixes 1.13+ support.

- plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
Currently, people can switch to the default channel with no problem, they can also send messages without any permissions being required but they won't see any messages sent in that channel, including their own.
I'm thinking if we should make it so the sender sees the message sent by them even if they don't have permission to see messages sent in that channel since right now someone could maybe accidentally or intentionally send a message in a channel and just not realize it was ever sent.
https://github.com/HelpChat/ChatChat/blob/0ad4db59553857c5349661decbd939662187fbc0/plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java#L222
> Messages sent in the default channel will be seen by everyone

- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/Kyorifier.java
- plugin/src/main/java/at/helpch/chatchat/util/PapiTagUtils.java
This adds 2 new tags that can be used in formats. These tags have 1 argument which can be either `closing` or `inserting`.
<b>How it works:</b>
Let's say we have a essentials nickname `&3Blitz`, and a format that looks like this:
```yml
parts:
name:
- '<white>TEST <papi:closing:essentials_nickname>: <message>'
```
In this format, the output in chat when sending a message `HELLOOO` will be something like this: 
But now if we change the `closing` argument with `inserting`, it will look like this:
It works the same with the `<papi-rel>` tag but that one is for relational placeholders.
I am looking for feedback on this! 
<b>A few ideas:</b>
- We could add an extra argument for kyorify and remove the support for `%placeholder%` placeholders. What do you guys think about that? 
- Currently the …
> Added <papi> and <papi-rel> tags

- api/src/main/java/at/helpch/chatchat/api/ChatUser.java
- api/src/main/java/at/helpch/chatchat/api/User.java
- plugin/build.gradle.kts
- plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
- plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java
- plugin/src/main/java/at/helpch/chatchat/command/IgnoreCommand.java
- plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java
- plugin/src/main/java/at/helpch/chatchat/data/impl/gson/ChatUserAdapter.java
- plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java
- plugin/src/main/java/at/helpch/chatchat/user/ConsoleUser.java
- plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
Resolves #80
Added `/ignore <player>`
Permission: `chatchat.ignore`
Bypass Permission: `chatchat.ignore.bypass`
This probably shouldn't be merged until the storage system is setup that way ignored players will be saved across restarts. Marked as draft for now.
> Add a /ignore command

- api/src/main/java/at/helpch/chatchat/api/event/PMSendEvent.java
It seems like this has been forgotten for the PMSendEvent, the ChatChatEvent and MentionEvent both have this, but this one doesn't.
> Added getHandlerList for PMSendEvent

- plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
- plugin/src/main/java/at/helpch/chatchat/command/ReplyCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/config/ConfigFactory.java
- plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
- plugin/src/main/java/at/helpch/chatchat/config/holder/ChannelsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/holder/FormatsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/holder/MessagesHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/holder/PMSettingsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/holder/SettingsHolder.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
- plugin/src/main/resources/settings.yml
DeluxeChat had this option so its basically a parity feature that was missing. This does change the config.yml options a bit tho.
The way it works:
- If its enabled, you disable it and do /chatchat reload, you will get the "invalid command" message.
- if its enabled, you disable it and you restart the server, the PM related commands will not be registered at all.
- If its disabled and you enable it, it will require a restart for the commands to be registered.
Closes #135
> Added a way to completely disable PMs on the server

- plugin/src/main/java/at/helpch/chatchat/util/PapiTagUtils.java
What the title says. The `<papi:PLACEHOLDER>` tag wasn't working unless the `inserting` or `closing` arguments were present. It should've instead defaulted to closing. Also the papi-rel tag was working a bit differently than the papi tag which was a bug.
Closes #162
> Fixed papi tag sometimes not parsing, and updated the papi-rel tag to work like the papi tag.

- plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
- plugin/src/main/java/at/helpch/chatchat/command/ReloadCommand.java
- plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
- plugin/src/main/java/at/helpch/chatchat/config/DefaultConfigObjects.java
- plugin/src/main/java/at/helpch/chatchat/config/holder/FormatsHolderImpl.java
- plugin/src/main/java/at/helpch/chatchat/config/mapper/ChannelMapper.java
- Fixed wrong channel formats path. From `channels.<channel-name>.formats.formats.<format-name>` to `channels.<channel-name>.formats.<format-name>`
- Fixed wrong message being sent on /chatchat reload when the number of loaded formats and/or channels were 1
- Added a console warning when the default channel can't be loaded/found to let the user know that an internal channel will be used.
- Listed the number of channel formats that were loaded on /chatchat reload
- Listed the number of formats, channels and channel formats that were loaded on startup (in console)
- Removed the default channel formats. They were only creating confusion for new people.
Tested all the features locally and also just provided a jar in discord for people to test.
> Some small fixes and quality of life improvements.

- plugin/src/main/java/at/helpch/chatchat/config/ConfigFactory.java
- plugin/src/main/java/at/helpch/chatchat/config/ConfigManager.java
- plugin/src/main/java/at/helpch/chatchat/config/holder/AddonsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/holder/ExtensionsHolder.java
- plugin/src/main/java/at/helpch/chatchat/config/mapper/AddonsMapper.java
- plugin/src/main/java/at/helpch/chatchat/hooks/HookManagerImpl.java
- plugin/src/main/java/at/helpch/chatchat/hooks/dsrv/ChatChatDsrvHook.java
- plugin/src/main/java/at/helpch/chatchat/hooks/towny/ChatChatTownyHook.java
- plugin/src/main/java/at/helpch/chatchat/hooks/vanish/EssentialsVanishHook.java
- plugin/src/main/java/at/helpch/chatchat/hooks/vanish/SuperVanishHook.java
- plugin/src/main/java/at/helpch/chatchat/rule/RuleManagerImpl.java
- plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
- plugin/src/main/resources/extensions.yml
Added a new `extensions.yml` file. From that file, users can enable or disable certain features of ChatChat. These features are mostly addons that add compatibility with other plugins but also extra features that are made to replicate the way another plugin works.
A few examples:
- DeluxeChat inverse priorities - in [DeluxeChat](https://www.spigotmc.org/resources/1277/), lower number = higher priority and this can be replicated in ChatChat
- DeluxeChat utf-8 rule - in [DeluxeChat](https://www.spigotmc.org/resources/1277/), using non ASCII characters is locked behind a permission. This can be replicated in ChatChat
- Towny addon - adds ability to create [Towny](https://github.com/TownyAdvanced/Towny) nation and town channels.
- DiscordSRV addon - adds support for cross platform (Minecraft …
> Configurable extensions

- plugin/src/main/java/at/helpch/chatchat/data/impl/gson/GsonDatabase.java
- plugin/src/main/java/at/helpch/chatchat/listener/PlayerListener.java
- plugin/src/main/java/at/helpch/chatchat/user/UsersHolderImpl.java
Users are loaded and unloaded on PlayerJoin/Quit sync, which cause some overheat
> feat: make user (un)loading async

- api/build.gradle.kts
- gradle/libs.versions.toml
- plugin/build.gradle.kts
updated adventure lib to support 1.20.2
supervanish also needed to be updated as the old version failed to build
> 1.20.2 support (updated adventure)

- gradle/libs.versions.toml
It seems that only hover was broken on 1.20.4. Tested on 1.20.4, basic features (including hover) work.
> Add 1.20.x support

- plugin/src/main/java/at/helpch/chatchat/command/SwitchChannelCommand.java
- plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
- plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
Resolves issue #218
In the console format for ChatChat, if I use %chatchat_channel_name% - it always returns default, unless the person is in the dedicated channel.
I have a staff chat - and you can use /staff or use the @ prefix to send a message.
However, If I use the prefix, the message will successfully go to console and the proper chat in-game, but the %chatchat_channel_name% still returns default channel in console format, rather than staff channel.
> Resolve #218

- api/src/main/java/at/helpch/chatchat/api/user/ChatUser.java
- plugin/src/main/java/at/helpch/chatchat/ChatChatPlugin.java
- plugin/src/main/java/at/helpch/chatchat/command/FormatTestCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/IgnoreCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/UnignoreCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/hooks/dsrv/DsrvListener.java
- plugin/src/main/java/at/helpch/chatchat/hooks/vanish/EssentialsVanishHook.java
- plugin/src/main/java/at/helpch/chatchat/hooks/vanish/SuperVanishHook.java
- plugin/src/main/java/at/helpch/chatchat/hooks/vanish/VanillaVanishHook.java
- plugin/src/main/java/at/helpch/chatchat/placeholder/MiniPlaceholderImpl.java
- plugin/src/main/java/at/helpch/chatchat/placeholder/PlaceholderAPIPlaceholders.java
- plugin/src/main/java/at/helpch/chatchat/rule/InvalidCharsRule.java
- plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java
- plugin/src/main/java/at/helpch/chatchat/util/ChannelUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/MentionUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
- plugin/src/main/java/at/helpch/chatchat/util/PapiTagUtils.java
Fixes #231
Edit by @BlitzOffline:
Fixes #158
> fix: bukkit player api usage

- api/src/main/java/at/helpch/chatchat/api/user/ChatUser.java
- gradle/libs.versions.toml
- plugin/src/main/java/at/helpch/chatchat/command/FormatTestCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/IgnoreCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/UnignoreCommand.java
- plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java
- plugin/src/main/java/at/helpch/chatchat/config/holder/MessagesHolder.java
- plugin/src/main/java/at/helpch/chatchat/hooks/dsrv/DsrvListener.java
- plugin/src/main/java/at/helpch/chatchat/listener/ChatListener.java
- plugin/src/main/java/at/helpch/chatchat/placeholder/PlaceholderAPIPlaceholders.java
- plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java
- plugin/src/main/java/at/helpch/chatchat/util/ChannelUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/MentionUtils.java
- plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java
- plugin/src/main/resources/messages.yml
- removes ChatUser#playerNotNull in favor of using the ChatUser#player method which returns an optional (as discussed here: https://github.com/HelpChat/ChatChat/pull/232#issuecomment-2079066457)
- upgrades adventure (for 1.20.5 and 1.20.6 support)
- fixes 2 bugs introduced in PR #232:
- Player#toString being used instead of Player#getName in mention parsing which led to a regex exception being thrown
- ChatChatPlugin#audiences being used in a try block resulted in it being closed after the first use
Tested on:
- `git-Paper-496 (MC: 1.20.4)`
- `Java 17 (OpenJDK 64-Bit Server VM 17.0.5+8)`
- `Linux 5.15.146.1-microsoft-standard-WSL2 (amd64)`
> Fix issues introduced in PR #232
